services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moviebox-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:5001/api/auth
      - NEXT_PUBLIC_MOVIE_API_URL=http://localhost:5002/api/movies
      - NEXT_PUBLIC_COLLECTION_API_URL=http://localhost:5002/api/collections
      - NEXT_PUBLIC_FAVORITE_API_URL=http://localhost:5002/api/favorites
      - NEXT_PUBLIC_PERSON_API_URL=http://localhost:5002/api/person
    depends_on:
      - auth-service
      - movie-service
    restart: always

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: moviebox-auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI:-mongodb+srv://hasnain:3718@cluster0.arb20r6.mongodb.net/?appName=Cluster0}
      - JWT_SECRET=${JWT_SECRET:-9d097df9bb52b437e025bae9b17320dc72792f156db74866ea4ac7b3d7bc24ea}
    restart: always

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    container_name: moviebox-movie-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=${MONGO_URI:-mongodb+srv://hasnain:3718@cluster0.arb20r6.mongodb.net/?appName=Cluster0}
      - TMDB_API_KEY=${TMDB_API_KEY:-e0c2c693d80345a911fac92dbf1b27dd}
      - OMDB_API_KEY=${OMDB_API_KEY:-f4dc3b7f}
      - JWT_SECRET=${JWT_SECRET:-9d097df9bb52b437e025bae9b17320dc72792f156db74866ea4ac7b3d7bc24ea}
    restart: always
