apiVersion: v1
kind: Secret
metadata:
  name: moviebox-secrets
  labels:
    app.kubernetes.io/name: moviebox-secrets
    app.kubernetes.io/part-of: the-moviebox
type: Opaque
stringData:
  # Real Plaintext Credentials (Kubernetes automatically converts stringData to Base64)
  MONGO_URI: "mongodb+srv://hasnain:3718@cluster0.arb20r6.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "9d097df9bb52b437e025bae9b17320dc72792f156db74866ea4ac7b3d7bc24ea"
  TMDB_API_KEY: "e0c2c693d80345a911fac92dbf1b27dd"
  OMDB_API_KEY: "f4dc3b7f"
