apiVersion: v1
kind: Secret
metadata:
  name: moviebox-secrets
  labels:
    app.kubernetes.io/name: moviebox-secrets
    app.kubernetes.io/part-of: the-moviebox
type: Opaque
stringData:
  # Replace placeholders with your actual base64/plaintext credentials locally
  MONGO_URI: "mongodb+srv://<DB_USER>:<DB_PASSWORD>@cluster0.mongodb.net/moviebox"
  JWT_SECRET: "YOUR_SUPER_SECURE_JWT_SECRET_KEY"
  TMDB_API_KEY: "YOUR_TMDB_API_KEY"
  OMDB_API_KEY: "YOUR_OMDB_API_KEY"
